CREATE TABLE Reviews(
    userID VARCHAR(100) FOREIGN KEY REFERENCES Users(userID),
    tourID VARCHAR(100) FOREIGN KEY REFERENCES Tours(tourID),
    rating INT NOT NULL,
    comment VARCHAR(400) NOT NULL
)

SELECT * from Reviews;